"use client";

import Button from "@/components/ui/button";
import { EmptyBlock, ErrorBlock, LoadingBlock } from "@/components/ui/feedback";
import { useAuth } from "@/contexts/auth-context";
import { createComment, deleteComment, getComments, updateComment } from "@/lib/api/comments";
import type { CommentListResponse } from "@/types/comment";
import type { WorkspaceRole } from "@/types/workspace";
import { type SubmitEvent, useEffect, useState } from "react";

export default function CommentThread({ workspaceId, projectId, issueId, role, archived }: { workspaceId: string; projectId: string; issueId: string; role: WorkspaceRole; archived: boolean }) {
  const { accessToken, user } = useAuth(); const [data, setData] = useState<CommentListResponse | null>(null); const [content, setContent] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [editContent, setEditContent] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [reload, setReload] = useState(0);
  useEffect(() => { if (!accessToken) return; const controller = new AbortController(); setLoading(true); setError(null); getComments(accessToken, workspaceId, projectId, issueId, 1, controller.signal).then(setData).catch((value: unknown) => { if (!controller.signal.aborted) setError(value instanceof Error ? value.message : "Unable to load comments"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [accessToken, workspaceId, projectId, issueId, reload]);
  async function submit(event: SubmitEvent<HTMLFormElement>) { event.preventDefault(); if (!accessToken || !content.trim()) return; setBusy(true); setError(null); try { await createComment(accessToken, workspaceId, projectId, issueId, content.trim()); setContent(""); setReload((v) => v + 1); } catch (value) { setError(value instanceof Error ? value.message : "Unable to add comment"); } finally { setBusy(false); } }
  async function saveEdit(commentId: string) { if (!accessToken || editContent.trim().length < 2) return; setBusy(true); try { await updateComment(accessToken, workspaceId, projectId, issueId, commentId, editContent.trim()); setEditingId(null); setReload((v) => v + 1); } catch (value) { setError(value instanceof Error ? value.message : "Unable to edit comment"); } finally { setBusy(false); } }
  async function remove(commentId: string) { if (!accessToken || !window.confirm("Delete this comment?")) return; try { await deleteComment(accessToken, workspaceId, projectId, issueId, commentId); setReload((v) => v + 1); } catch (value) { setError(value instanceof Error ? value.message : "Unable to delete comment"); } }
  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Discussion</h2><p className="mt-1 text-sm text-slate-500">Share decisions, progress, and implementation notes.</p>{!archived && <form onSubmit={submit} className="mt-5"><textarea aria-label="New comment" rows={3} maxLength={5000} value={content} onChange={(e) => setContent(e.target.value)} placeholder="Write a comment..." className="w-full resize-none rounded-xl border border-slate-300 bg-white p-3 text-sm text-slate-900 outline-none placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /><div className="mt-2 flex justify-end"><Button type="submit" disabled={busy || !content.trim()}>{busy ? "Posting..." : "Post comment"}</Button></div></form>}{error && <div className="mt-5"><ErrorBlock message={error} onRetry={() => setReload((v) => v + 1)} /></div>}<div className="mt-6">{loading ? <LoadingBlock label="Loading comments..." /> : !data || data.comments.length === 0 ? <EmptyBlock title="No comments yet" description="Start the conversation with the first update." /> : <div className="space-y-4">{data.comments.map((comment) => { const own = comment.author.id === user?.id; const canDelete = own || role !== "MEMBER"; return <article key={comment.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-indigo-100 text-sm font-bold text-indigo-700">{comment.author.name.charAt(0).toUpperCase()}</span><div><p className="text-sm font-semibold text-slate-900">{comment.author.name}</p><p className="text-xs text-slate-500">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(comment.createdAt))}</p></div></div>{!archived && <div className="flex gap-2">{own && <button className="text-xs font-medium text-indigo-600" onClick={() => { setEditingId(comment.id); setEditContent(comment.content); }}>Edit</button>}{canDelete && <button className="text-xs font-medium text-red-600" onClick={() => void remove(comment.id)}>Delete</button>}</div>}</div>{editingId === comment.id ? <div className="mt-4"><textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} className="w-full rounded-lg border border-slate-300 bg-white p-3 text-sm text-slate-900 outline-none placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /><div className="mt-2 flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditingId(null)}>Cancel</Button><Button disabled={busy || editContent.trim().length < 2} onClick={() => void saveEdit(comment.id)}>Save</Button></div></div> : <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-700">{comment.content}</p>}</article>; })}</div>}</div></section>;
}
